/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_App */

#ifndef _Included_jni_App
#define _Included_jni_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_App
 * Method:    nativeVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_App_nativeVersion
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_init
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_main
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    task_1ms
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_task_11ms
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    task_2ms
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_task_12ms
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    task_4ms
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_task_14ms
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    task_8ms
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_task_18ms
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    task_16ms
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_task_116ms
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    task_32ms
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_task_132ms
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    task_64ms
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_task_164ms
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    task_128ms
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_task_1128ms
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    timer0_ovf
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_timer0_1ovf
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    timer1_ovf
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_timer1_1ovf
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    timer2_ovf
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_App_timer2_1ovf
  (JNIEnv *, jobject);

/*
 * Class:     jni_App
 * Method:    uart_isr
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_jni_App_uart_1isr
  (JNIEnv *, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
